export const legalContent = {
  de: {
    updated: "Stand: 21. September 2026",
    legal: {
      sections: [
        { title: "Angaben gemäß § 5 DDG", paragraphs: ["LinkedLab ist derzeit keine im Handelsregister eingetragene Gesellschaft. Anbieter dieses digitalen Dienstes und inhaltlich verantwortlich ist die unten genannte natürliche Person."] },
        { title: "Kontakt", kind: "contact" },
        { title: "Register- und Steuerangaben", kind: "registration" },
        { title: "Verantwortlich für den Inhalt", kind: "responsible" },
        { title: "Verbraucherstreitbeilegung", paragraphs: ["Der Anbieter ist nicht verpflichtet und derzeit nicht bereit, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen."] },
        { title: "Haftung für Inhalte", paragraphs: ["Als Diensteanbieter ist LinkedLab für eigene Inhalte nach den allgemeinen Gesetzen verantwortlich. Eine Verpflichtung, übermittelte oder gespeicherte fremde Informationen dauerhaft zu überwachen, besteht nur im Rahmen der gesetzlichen Vorgaben. Bei Bekanntwerden konkreter Rechtsverletzungen werden betroffene Inhalte unverzüglich entfernt."] },
        { title: "Externe Links", paragraphs: ["Diese Website enthält Links zu externen Angeboten, unter anderem Instagram, WhatsApp und veröffentlichten Kundenprojekten. Auf deren Inhalte und Datenschutzpraktiken hat LinkedLab keinen Einfluss. Zum Zeitpunkt der Verlinkung waren keine Rechtsverstöße erkennbar; rechtswidrige Links werden nach Bekanntwerden entfernt."] },
        { title: "Urheberrecht", paragraphs: ["Texte, Gestaltung, Grafiken und sonstige eigene Inhalte dieser Website unterliegen dem geltenden Urheberrecht. Eine Vervielfältigung oder Nutzung außerhalb der gesetzlichen Schranken bedarf der vorherigen Zustimmung des jeweiligen Rechteinhabers."] }
      ]
    },
    privacy: {
      sections: [
        { title: "1. Verantwortlicher", kind: "controller" },
        { title: "2. Hosting und Server-Logdaten", paragraphs: ["Diese Website wird über Vercel bereitgestellt. Beim Aufruf können technisch erforderliche Daten verarbeitet werden, insbesondere IP-Adresse, Datum und Uhrzeit, aufgerufene URL, Referrer, Browser-/Geräteinformationen und technische Anfragedaten. Die Verarbeitung dient der sicheren, stabilen und schnellen Bereitstellung der Website auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO.", "Hosting-Anbieter ist Vercel Inc. Vercel kann Daten auch in den USA verarbeiten. Hierfür kommen die jeweils anwendbaren Garantien für internationale Datenübermittlungen zum Einsatz. Weitere Informationen finden Sie in der Datenschutzerklärung und dem Data Processing Addendum von Vercel."] },
        { title: "3. Kontakt per E-Mail, WhatsApp oder Instagram", paragraphs: ["Wenn Sie LinkedLab kontaktieren, werden Ihre Kontaktdaten, der Inhalt Ihrer Nachricht und die für die Bearbeitung notwendigen Metadaten verarbeitet. Dies geschieht zur Durchführung vorvertraglicher Maßnahmen oder zur Vertragsabwicklung nach Art. 6 Abs. 1 lit. b DSGVO sowie, bei allgemeinen Anfragen, aufgrund des berechtigten Interesses an einer geordneten Kommunikation nach Art. 6 Abs. 1 lit. f DSGVO.", "WhatsApp und Instagram sind Dienste von Unternehmen der Meta-Gruppe. Beim Öffnen dieser externen Links gelten deren eigene Datenschutzbestimmungen; dabei kann eine Verarbeitung außerhalb der EU bzw. des EWR stattfinden. LinkedLab übermittelt durch das bloße Anzeigen dieser Website keine Daten aktiv an Meta."] },
        { title: "4. Vercel Web Analytics", paragraphs: ["LinkedLab verwendet Vercel Web Analytics, um die Nutzung dieser Website in aggregierter Form zu messen und das Angebot technisch und inhaltlich zu verbessern. Erfasst werden können insbesondere Zeitpunkt, aufgerufene URL, dynamischer Pfad, Referrer, gefilterte Abfrageparameter, ungefähre Geolokalisierung, Betriebssystem, Browser, Gerätetyp und Version des Analyseskripts.", "Vercel Web Analytics arbeitet ohne Cookies. Ereignisse werden laut Vercel anonym aufgezeichnet und weder einer Person noch einer IP-Adresse zugeordnet. Besucher werden für die Messung über einen aus der eingehenden Anfrage erzeugten Hash unterschieden; die Besuchersitzung wird nach 24 Stunden verworfen. Es erfolgt keine anwendungs- oder websiteübergreifende Nachverfolgung.", "Die Verarbeitung erfolgt zur Reichweitenmessung und Verbesserung des Webangebots auf Grundlage des berechtigten Interesses gemäß Art. 6 Abs. 1 lit. f DSGVO. Anbieter ist Vercel Inc.; eine Verarbeitung in den USA kann unter den jeweils anwendbaren Garantien für internationale Datenübermittlungen stattfinden."] },
        { title: "5. Cookies und Einwilligungsverwaltung", paragraphs: ["LinkedLab setzt eine technisch notwendige First-Party-Cookie-Einstellung ein, um Ihre Cookie-Auswahl für 180 Tage zu speichern. Rechtsgrundlage für das Speichern beziehungsweise Auslesen ist § 25 Abs. 2 TDDDG; die damit verbundene Verarbeitung erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO.", "Vercel Web Analytics verwendet keine Cookies und ist daher nicht von der Auswahl optionaler Analyse-Cookies abhängig. Derzeit sind keine optionalen Analyse- oder Marketing-Cookies eingebunden. Falls solche Dienste später aktiviert werden, erfolgt dies erst nach Ihrer Einwilligung gemäß § 25 Abs. 1 TDDDG und Art. 6 Abs. 1 lit. a DSGVO. Eine Einwilligung kann jederzeit über „Cookies verwalten“ widerrufen werden."] },
        { title: "6. Speicherdauer", paragraphs: ["Personenbezogene Daten werden nur so lange gespeichert, wie es für den jeweiligen Zweck erforderlich ist oder gesetzliche Aufbewahrungspflichten bestehen. Anfragen werden nach Abschluss der Bearbeitung gelöscht, sofern keine Vertrags-, Nachweis- oder Aufbewahrungspflichten entgegenstehen. Technische Protokolldaten werden nach den für den Hostingbetrieb erforderlichen Fristen verarbeitet. Die für Vercel Web Analytics erzeugte Besuchersitzung wird nach 24 Stunden verworfen."] },
        { title: "7. Empfänger und Übermittlungen", paragraphs: ["Empfänger können technische Dienstleister sein, die zur Bereitstellung der Website, Reichweitenmessung oder Kommunikation eingesetzt werden. Eine Weitergabe erfolgt nur, soweit sie für den jeweiligen Zweck erforderlich ist, eine gesetzliche Pflicht besteht oder eine wirksame Einwilligung vorliegt."] },
        { title: "8. Ihre Rechte", paragraphs: ["Sie haben nach Maßgabe der DSGVO das Recht auf Auskunft, Berichtigung, Löschung, Einschränkung der Verarbeitung, Datenübertragbarkeit und Widerspruch. Eine erteilte Einwilligung können Sie jederzeit mit Wirkung für die Zukunft widerrufen. Zur Ausübung Ihrer Rechte genügt eine Nachricht an die oben genannte E-Mail-Adresse."] },
        { title: "9. Beschwerderecht", paragraphs: ["Sie können sich bei einer Datenschutzaufsichtsbehörde beschweren. Zuständig für Baden-Württemberg ist der Landesbeauftragte für den Datenschutz und die Informationsfreiheit Baden-Württemberg, Lautenschlagerstraße 20, 70173 Stuttgart, Deutschland, www.baden-wuerttemberg.datenschutz.de."] },
        { title: "10. Automatisierte Entscheidungen", paragraphs: ["Es findet keine automatisierte Entscheidungsfindung einschließlich Profiling statt."] }
      ]
    },
    cookies: {
      sections: [
        { title: "Was sind Cookies?", paragraphs: ["Cookies sind kleine Textinformationen, die ein Browser auf dem Endgerät speichert. Sie können technisch notwendig sein oder – nach Einwilligung – für Analyse und Marketing eingesetzt werden."] },
        { title: "Welche Cookies verwendet LinkedLab?", kind: "cookieTable" },
        { title: "Cookie-freie Reichweitenmessung", paragraphs: ["Vercel Web Analytics ist aktiv und misst Seitenaufrufe in aggregierter Form, verwendet dafür jedoch keine Cookies. Es werden weder Analyse- noch Werbe-Cookies durch diesen Dienst gesetzt. Weitere Einzelheiten finden Sie in der Datenschutzerklärung."] },
        { title: "Optionale Kategorien", paragraphs: ["Optionale Analyse- und Marketing-Cookies können im Einstellungsfenster ausgewählt werden, sind aber derzeit technisch nicht mit einem Dienst verbunden. Vor einer späteren Aktivierung wird diese Richtlinie aktualisiert."] },
        { title: "Auswahl ändern oder widerrufen", paragraphs: ["Über „Cookies verwalten“ im Footer können Sie Ihre Entscheidung jederzeit ändern. Sie können Cookies außerdem über die Einstellungen Ihres Browsers löschen. Notwendige Cookies sind für das Speichern Ihrer Auswahl erforderlich."] },
        { title: "Externe Links", paragraphs: ["Erst wenn Sie einen Link zu WhatsApp, Instagram oder einer anderen externen Website öffnen, kann der jeweilige Anbieter eigene Cookies oder ähnliche Technologien einsetzen. Darauf hat LinkedLab keinen Einfluss."] }
      ]
    }
  },
  en: {
    updated: "Last updated: 21 September 2026",
    legal: { sections: [
      { title: "Information pursuant to section 5 DDG", paragraphs: ["LinkedLab is not currently a company entered in the commercial register. The provider of this digital service and the person responsible for its content is the individual named below."] },
      { title: "Contact", kind: "contact" }, { title: "Registration and tax details", kind: "registration" }, { title: "Responsible for content", kind: "responsible" },
      { title: "Consumer dispute resolution", paragraphs: ["The provider is neither obliged nor currently willing to participate in dispute resolution proceedings before a consumer arbitration board."] },
      { title: "Liability for content", paragraphs: ["LinkedLab is responsible for its own content under general law. Third-party information is monitored only where required by law. Content will be removed promptly if a specific infringement becomes known."] },
      { title: "External links", paragraphs: ["This website links to external services including Instagram, WhatsApp and published client projects. LinkedLab has no control over their content or privacy practices. Unlawful links will be removed when identified."] },
      { title: "Copyright", paragraphs: ["Original text, design, graphics and other content on this website are protected by applicable copyright law. Use beyond statutory exceptions requires the prior consent of the relevant rights holder."] }
    ] },
    privacy: { sections: [
      { title: "1. Controller", kind: "controller" },
      { title: "2. Hosting and server logs", paragraphs: ["This website is delivered through Vercel. When you visit, technically necessary information may be processed, including IP address, date and time, requested URL, referrer, browser/device details and request metadata. This is necessary to provide a secure, stable and fast website and is based on Article 6(1)(f) GDPR.", "The hosting provider is Vercel Inc. Vercel may process information in the United States using the applicable safeguards for international transfers. More information is available in Vercel's Privacy Notice and Data Processing Addendum."] },
      { title: "3. Contact by email, WhatsApp or Instagram", paragraphs: ["If you contact LinkedLab, your contact details, message and necessary metadata are processed to answer your enquiry. The legal basis is Article 6(1)(b) GDPR for pre-contractual or contractual communication and Article 6(1)(f) GDPR for general enquiries.", "WhatsApp and Instagram are services of companies in the Meta group. Their own privacy terms apply after you open an external link and data may be processed outside the EU/EEA. Simply displaying this website does not actively transfer your data to Meta."] },
      { title: "4. Vercel Web Analytics", paragraphs: ["LinkedLab uses Vercel Web Analytics to measure website use in aggregate and improve the site's technical performance and content. The service may collect the event time, requested URL, dynamic path, referrer, filtered query parameters, approximate geolocation, operating system, browser, device type and analytics script version.", "Vercel Web Analytics operates without cookies. According to Vercel, events are recorded anonymously and are not tied to an individual or IP address. Visitors are distinguished for measurement using a hash created from the incoming request, and the visitor session is discarded after 24 hours. There is no tracking across applications or websites.", "Processing is based on LinkedLab's legitimate interest in measuring reach and improving this website under Article 6(1)(f) GDPR. The provider is Vercel Inc.; data may be processed in the United States under the applicable safeguards for international transfers."] },
      { title: "5. Cookies and consent", paragraphs: ["LinkedLab uses one necessary first-party cookie to store your cookie selection for 180 days. Storage and access are based on section 25(2) TDDDG, and related personal-data processing is based on Article 6(1)(f) GDPR.", "Vercel Web Analytics does not use cookies and therefore does not depend on the optional analytics-cookie setting. No optional analytics or marketing cookies are currently integrated. If such services are introduced, they will only run after consent under section 25(1) TDDDG and Article 6(1)(a) GDPR. Consent can be withdrawn at any time through “Manage cookies”."] },
      { title: "6. Retention", paragraphs: ["Personal data is kept only for as long as necessary for the relevant purpose or a statutory retention requirement. Enquiries are deleted after completion unless contractual, evidentiary or legal retention duties apply. Technical logs are processed for the periods necessary to operate the hosting service. The visitor session created for Vercel Web Analytics is discarded after 24 hours."] },
      { title: "7. Recipients and transfers", paragraphs: ["Recipients may include technical service providers used to deliver the website, measure reach or manage communications. Data is shared only where necessary for the relevant purpose, required by law, or covered by valid consent."] },
      { title: "8. Your rights", paragraphs: ["Subject to the GDPR, you may request access, rectification, erasure, restriction, portability and object to processing. You may withdraw consent at any time for the future. Contact the email address above to exercise your rights."] },
      { title: "9. Right to complain", paragraphs: ["You may complain to a data protection authority. The competent authority in Baden-Württemberg is the State Commissioner for Data Protection and Freedom of Information, Lautenschlagerstraße 20, 70173 Stuttgart, Germany, www.baden-wuerttemberg.datenschutz.de."] },
      { title: "10. Automated decisions", paragraphs: ["LinkedLab does not use automated decision-making or profiling."] }
    ] },
    cookies: { sections: [
      { title: "What are cookies?", paragraphs: ["Cookies are small pieces of text stored by a browser on a device. They may be technically necessary or, with consent, used for analytics and marketing."] },
      { title: "Cookies used by LinkedLab", kind: "cookieTable" },
      { title: "Cookie-free audience measurement", paragraphs: ["Vercel Web Analytics is active and measures page views in aggregate, but it does not use cookies. The service does not set analytics or advertising cookies. See the privacy policy for further details."] },
      { title: "Optional categories", paragraphs: ["Optional analytics and marketing cookies can be selected in the settings panel, but no service is currently connected to either category. This policy will be updated before such services are activated."] },
      { title: "Change or withdraw your choice", paragraphs: ["Use “Manage cookies” in the footer to change your selection at any time. You can also delete cookies through your browser settings. The necessary cookie is required to remember your choice."] },
      { title: "External links", paragraphs: ["A third-party provider may use its own cookies or similar technology only after you open a link to WhatsApp, Instagram or another external website. LinkedLab has no control over those technologies."] }
    ] }
  },
  es: {
    updated: "Última actualización: 21 de septiembre de 2026",
    legal: { sections: [
      { title: "Información conforme al § 5 DDG", paragraphs: ["LinkedLab no es actualmente una sociedad inscrita en el registro mercantil. El prestador de este servicio digital y responsable de sus contenidos es la persona física indicada a continuación."] },
      { title: "Contacto", kind: "contact" }, { title: "Datos registrales y fiscales", kind: "registration" }, { title: "Responsable del contenido", kind: "responsible" },
      { title: "Resolución de conflictos de consumo", paragraphs: ["El responsable no está obligado ni actualmente dispuesto a participar en procedimientos de resolución de conflictos ante una junta arbitral de consumo."] },
      { title: "Responsabilidad por los contenidos", paragraphs: ["LinkedLab responde de sus contenidos propios conforme a la legislación general. La información de terceros se supervisará únicamente cuando lo exija la ley. Cualquier contenido ilícito del que se tenga conocimiento será retirado con prontitud."] },
      { title: "Enlaces externos", paragraphs: ["La web enlaza a servicios externos como Instagram, WhatsApp y proyectos de clientes publicados. LinkedLab no controla sus contenidos ni sus prácticas de privacidad. Los enlaces ilícitos se retirarán cuando se detecten."] },
      { title: "Propiedad intelectual", paragraphs: ["Los textos, el diseño, los gráficos y demás contenidos propios están protegidos por la legislación aplicable. Cualquier uso fuera de los límites legales requiere autorización previa del titular correspondiente."] }
    ] },
    privacy: { sections: [
      { title: "1. Responsable del tratamiento", kind: "controller" },
      { title: "2. Alojamiento y registros del servidor", paragraphs: ["Esta web se sirve mediante Vercel. Al visitarla pueden tratarse datos técnicamente necesarios como la dirección IP, fecha y hora, URL solicitada, página de procedencia, navegador, dispositivo y metadatos de la petición. El fin es ofrecer una web segura, estable y rápida, con base en el artículo 6.1.f del RGPD.", "El proveedor de alojamiento es Vercel Inc. Vercel puede tratar información en Estados Unidos aplicando las garantías correspondientes para transferencias internacionales. Hay más información en su Privacy Notice y Data Processing Addendum."] },
      { title: "3. Contacto por correo, WhatsApp o Instagram", paragraphs: ["Si contactas con LinkedLab, tratamos tus datos de contacto, el contenido del mensaje y los metadatos necesarios para responder. La base jurídica es el artículo 6.1.b del RGPD para comunicaciones precontractuales o contractuales y el artículo 6.1.f para consultas generales.", "WhatsApp e Instagram son servicios de empresas del grupo Meta. Al abrir esos enlaces externos se aplican sus propias políticas y puede haber tratamiento fuera de la UE o del EEE. La mera visualización de esta web no transmite activamente datos a Meta."] },
      { title: "4. Vercel Web Analytics", paragraphs: ["LinkedLab utiliza Vercel Web Analytics para medir de forma agregada el uso de esta web y mejorar su funcionamiento técnico y sus contenidos. El servicio puede recoger la fecha y hora del evento, URL visitada, ruta dinámica, página de procedencia, parámetros de consulta filtrados, geolocalización aproximada, sistema operativo, navegador, tipo de dispositivo y versión del script de analítica.", "Vercel Web Analytics funciona sin cookies. Según Vercel, los eventos se registran de forma anónima y no se asocian a una persona ni a una dirección IP. Para la medición, los visitantes se distinguen mediante un hash generado a partir de la petición entrante; la sesión del visitante se descarta después de 24 horas. No existe seguimiento entre aplicaciones o sitios web.", "El tratamiento se basa en el interés legítimo de LinkedLab de medir el alcance y mejorar esta web, conforme al artículo 6.1.f del RGPD. El proveedor es Vercel Inc.; puede existir tratamiento en Estados Unidos con las garantías aplicables a las transferencias internacionales."] },
      { title: "5. Cookies y consentimiento", paragraphs: ["LinkedLab utiliza una cookie propia y necesaria para guardar durante 180 días tu selección de cookies. Su almacenamiento o lectura se basa en el § 25.2 TDDDG y el tratamiento asociado en el artículo 6.1.f del RGPD.", "Vercel Web Analytics no utiliza cookies y, por tanto, no depende de la selección de cookies analíticas opcionales. Actualmente no hay cookies analíticas opcionales ni de marketing integradas. Si se incorporan servicios de este tipo, solo se ejecutarán después del consentimiento conforme al § 25.1 TDDDG y al artículo 6.1.a del RGPD. Puedes retirar el consentimiento en cualquier momento desde “Gestionar cookies”."] },
      { title: "6. Conservación", paragraphs: ["Los datos personales se conservan únicamente durante el tiempo necesario para su finalidad o para cumplir obligaciones legales. Las consultas se eliminan al finalizar su gestión, salvo que existan obligaciones contractuales, probatorias o legales. Los registros técnicos se tratan durante los plazos necesarios para operar el alojamiento. La sesión generada para Vercel Web Analytics se descarta después de 24 horas."] },
      { title: "7. Destinatarios y transferencias", paragraphs: ["Pueden ser destinatarios los proveedores técnicos necesarios para servir la web, medir su alcance o gestionar comunicaciones. Los datos solo se comunican cuando sea necesario para la finalidad correspondiente, exista una obligación legal o se haya otorgado consentimiento válido."] },
      { title: "8. Tus derechos", paragraphs: ["Conforme al RGPD puedes solicitar acceso, rectificación, supresión, limitación, portabilidad y oposición. También puedes retirar un consentimiento para el futuro. Para ejercer estos derechos basta con escribir al correo indicado arriba."] },
      { title: "9. Reclamaciones", paragraphs: ["Puedes reclamar ante una autoridad de protección de datos. La autoridad competente en Baden-Württemberg es el Landesbeauftragte für den Datenschutz und die Informationsfreiheit Baden-Württemberg, Lautenschlagerstraße 20, 70173 Stuttgart, Alemania, www.baden-wuerttemberg.datenschutz.de."] },
      { title: "10. Decisiones automatizadas", paragraphs: ["LinkedLab no utiliza decisiones automatizadas ni elaboración de perfiles."] }
    ] },
    cookies: { sections: [
      { title: "¿Qué son las cookies?", paragraphs: ["Las cookies son pequeños fragmentos de texto que el navegador guarda en el dispositivo. Pueden ser necesarias técnicamente o, con consentimiento, utilizarse para analítica y marketing."] },
      { title: "Cookies utilizadas por LinkedLab", kind: "cookieTable" },
      { title: "Medición de audiencia sin cookies", paragraphs: ["Vercel Web Analytics está activo y mide las visitas de forma agregada, pero no utiliza cookies. Este servicio no instala cookies analíticas ni publicitarias. Consulta la política de privacidad para más detalles."] },
      { title: "Categorías opcionales", paragraphs: ["Las cookies opcionales de analítica y marketing pueden seleccionarse en el panel, pero actualmente no hay ningún servicio conectado a esas categorías. Esta política se actualizará antes de activar dichos servicios."] },
      { title: "Cambiar o retirar la elección", paragraphs: ["Puedes abrir “Gestionar cookies” en el pie de página para cambiar tu elección cuando quieras. También puedes borrar cookies desde el navegador. La cookie necesaria permite recordar tu decisión."] },
      { title: "Enlaces externos", paragraphs: ["Solo al abrir un enlace a WhatsApp, Instagram u otra web externa, el proveedor correspondiente puede usar sus propias cookies o tecnologías similares. LinkedLab no controla esas tecnologías."] }
    ] }
  }
};
