export const partnerContent = {
  de: {
    seoTitle: "LinkedLab Partnerprogramm | 50 € pro Neukunde",
    seoDescription: "Empfehlen Sie LinkedLab weiter und erhalten Sie 50 € für jeden bestätigten, zahlenden Neukunden – bis zu 500 €.",
    kicker: "LinkedLab Partnerprogramm",
    title: "Gute Kontakte. Klare Empfehlung. Faire Provision.",
    intro: "Empfehlen Sie LinkedLab an Unternehmen, die eine professionelle Website oder ein einfaches digitales System brauchen. Für jeden bestätigten, zahlenden Neukunden erhalten Sie 50 €.",
    primaryCta: "Als Partner bewerben",
    secondaryCta: "So funktioniert es",
    metrics: [["50 €", "pro gültigem Neukunden"], ["500 €", "maximal pro Partner"], ["0 €", "Teilnahmegebühr"]],
    howKicker: "Einfacher Ablauf",
    howTitle: "In drei Schritten zur Provision.",
    howText: "Keine Plattform, kein kompliziertes Dashboard: persönliche Prüfung, eindeutiger Empfehlungscode und nachvollziehbare Bestätigung.",
    steps: [["01", "Bewerben", "Senden Sie das kurze Formular. LinkedLab prüft jede Bewerbung persönlich."], ["02", "Empfehlen", "Nach Freigabe erhalten Sie einen individuellen Code und einen Link für Ihre Kontakte."], ["03", "50 € erhalten", "Die Provision wird fällig, sobald der vermittelte Kunde sein Projekt bestätigt und bezahlt hat."]],
    calculatorKicker: "Provisionsrechner",
    calculatorTitle: "Was kann Ihre Empfehlung wert sein?",
    calculatorText: "Bewegen Sie den Regler. Der Höchstbetrag liegt bei zehn gültigen Neukunden.",
    clientsLabel: "Gültige Neukunden",
    earningsLabel: "Mögliche Provision",
    calculatorNote: "Eine Anfrage allein löst keine Provision aus. Es gelten bestätigte, bezahlte Projekte ohne Stornierung oder Erstattung.",
    audienceKicker: "Für wen es passt",
    audienceTitle: "Ideal für Menschen mit guten lokalen Kontakten.",
    audienceText: "Das Programm ist offen für Personen und kleine Unternehmen, die LinkedLab glaubwürdig weiterempfehlen können.",
    profiles: [["Freelancer & Berater", "Wenn Ihre Kunden regelmäßig Unterstützung bei Webauftritt, SEO oder digitalen Abläufen brauchen."], ["Agenturen & Kreative", "Wenn ein Projekt außerhalb Ihres eigenen Angebots liegt und Sie einen verlässlichen Partner empfehlen möchten."], ["Lokale Netzwerker", "Wenn Sie Unternehmer, Vereine oder Selbstständige in Ihrer Region miteinander verbinden."], ["Zufriedene Kunden", "Wenn Sie Ihre LinkedLab-Erfahrung an andere Unternehmen weitergeben möchten."]],
    formKicker: "Bewerbung",
    formTitle: "Partner werden.",
    formText: "Erzählen Sie uns kurz, wer Sie sind und wie Sie LinkedLab weiterempfehlen möchten. Die Prüfung und Freigabe erfolgen manuell.",
    fields: { name: "Name oder Unternehmen", email: "E-Mail-Adresse", channel: "Bevorzugter Kontaktkanal (optional)", activity: "Tätigkeit", message: "Kurze Nachricht (optional)" },
    placeholders: { name: "Ihr Name oder Firmenname", email: "name@beispiel.de", channel: "WhatsApp, Telefon, Instagram …", message: "Wie möchten Sie LinkedLab weiterempfehlen?" },
    activities: ["Bitte auswählen", "Freelancer / Berater", "Agentur / Kreativbetrieb", "Lokales Netzwerk", "Bestehender Kunde", "Sonstiges"],
    submit: "Bewerbung senden",
    sending: "Wird gesendet …",
    success: "Vielen Dank. Ihre Bewerbung wurde übermittelt. Wir melden uns nach der persönlichen Prüfung.",
    formNote: "Mit dem Absenden stimmen Sie der Verarbeitung Ihrer Angaben zur Prüfung Ihrer Bewerbung zu. Details finden Sie in der Datenschutzerklärung.",
    faqKicker: "FAQ",
    faqTitle: "Transparent, bevor Sie starten.",
    faqs: [["Wann zählt eine Empfehlung?", "Wenn ein neuer Kunde Ihren persönlichen Code verwendet, ein LinkedLab-Projekt bestätigt und die vereinbarte Zahlung eingegangen ist."], ["Gibt es Geld für einen Kontakt oder Lead?", "Nein. Eine Provision entsteht erst für einen bestätigten und zahlenden Neukunden."], ["Wie hoch ist die Provision?", "50 € pro gültigem Neukunden, bis zu zehn Kunden beziehungsweise insgesamt 500 € pro Partner."], ["Was passiert bei einer Stornierung oder Erstattung?", "Für stornierte oder erstattete Projekte wird keine Provision gezahlt. Bereits geplante Auszahlungen werden entsprechend korrigiert."], ["Wie werden Empfehlungen zugeordnet?", "Über Ihren persönlichen Code oder Link. Der Code wird während der Browser-Sitzung gespeichert und beim Kontakt an LinkedLab übertragen."], ["Gibt es ein Partner-Dashboard?", "Noch nicht. Freigaben, Bestätigungen und Auszahlungen werden in dieser ersten Version persönlich und manuell geführt."]],
    termsTitle: "Klare Bedingungen",
    terms: ["Die Teilnahme ist kostenlos und wird individuell freigegeben.", "Jeder Neukunde kann nur einmal einer Empfehlung zugeordnet werden.", "Provisionen werden nach Zahlungseingang und Ablauf möglicher Stornierungs- oder Erstattungsfälle bestätigt.", "Auszahlung und erforderliche steuerliche Belege werden vor Aktivierung des Partners individuell vereinbart.", "Die Teilnahme begründet kein Arbeitsverhältnis und kann bei Missbrauch beendet werden."],
    finalTitle: "Sie kennen ein Unternehmen, dem LinkedLab helfen kann?",
    finalText: "Bewerben Sie sich in wenigen Minuten. Nach der Prüfung erhalten Sie Ihren persönlichen Empfehlungscode.",
    privacyLink: "Datenschutzerklärung"
  },
  en: {
    seoTitle: "LinkedLab Partner Programme | €50 per new client",
    seoDescription: "Refer a business to LinkedLab and receive €50 for every confirmed paying new client, up to €500.",
    kicker: "LinkedLab Partner Programme",
    title: "Good connections. Clear referrals. Fair commission.",
    intro: "Recommend LinkedLab to businesses that need a professional website or a simple digital system. You receive €50 for every confirmed paying new client.",
    primaryCta: "Apply to become a partner",
    secondaryCta: "How it works",
    metrics: [["€50", "per valid new client"], ["€500", "maximum per partner"], ["€0", "participation fee"]],
    howKicker: "Simple process", howTitle: "Three steps to your commission.", howText: "No platform and no pretend dashboard: personal review, a unique referral code and a traceable confirmation.",
    steps: [["01", "Apply", "Send the short form. LinkedLab reviews every application personally."], ["02", "Refer", "Once approved, you receive a unique code and a link to share with your contacts."], ["03", "Receive €50", "Commission becomes payable once the referred client confirms and pays for their project."]],
    calculatorKicker: "Commission calculator", calculatorTitle: "What could your referrals be worth?", calculatorText: "Move the slider. The programme is capped at ten valid new clients.", clientsLabel: "Valid new clients", earningsLabel: "Potential commission", calculatorNote: "An enquiry alone does not qualify. Only confirmed, paid projects without cancellation or refund count.",
    audienceKicker: "Who it is for", audienceTitle: "Made for people with trusted business connections.", audienceText: "The programme is open to people and small businesses that can recommend LinkedLab credibly.",
    profiles: [["Freelancers & consultants", "When your clients regularly need support with websites, SEO or digital operations."], ["Agencies & creatives", "When a project sits outside your offer and you want to recommend a reliable partner."], ["Local connectors", "When you connect entrepreneurs, associations or self-employed professionals in your area."], ["Happy clients", "When you want to share your LinkedLab experience with another business."]],
    formKicker: "Application", formTitle: "Become a partner.", formText: "Tell us briefly who you are and how you would recommend LinkedLab. Review and approval are handled manually.",
    fields: { name: "Name or business", email: "Email address", channel: "Preferred contact channel (optional)", activity: "Activity", message: "Short message (optional)" },
    placeholders: { name: "Your name or business", email: "name@example.com", channel: "WhatsApp, phone, Instagram …", message: "How would you recommend LinkedLab?" },
    activities: ["Please select", "Freelancer / consultant", "Agency / creative business", "Local network", "Existing client", "Other"],
    submit: "Send application", sending: "Sending …", success: "Thank you. Your application has been submitted. We will get back to you after a personal review.",
    formNote: "By submitting, you agree to the processing of your details to review your application. See the privacy policy for details.",
    faqKicker: "FAQ", faqTitle: "Transparent before you start.",
    faqs: [["When does a referral count?", "When a new client uses your personal code, confirms a LinkedLab project and the agreed payment has been received."], ["Do I get paid for a contact or lead?", "No. Commission only arises for a confirmed, paying new client."], ["How much is the commission?", "€50 per valid new client, up to ten clients or €500 in total per partner."], ["What happens after a cancellation or refund?", "No commission is paid for cancelled or refunded projects. Any scheduled payout is adjusted accordingly."], ["How are referrals attributed?", "Through your personal code or link. The code is retained during the browser session and passed to LinkedLab when contact is made."], ["Is there a partner dashboard?", "Not yet. In this first version, approvals, confirmations and payouts are handled personally and recorded manually."]],
    termsTitle: "Clear terms", terms: ["Participation is free and individually approved.", "Each new client can only be attributed to one referral.", "Commission is confirmed after payment and any cancellation or refund case has been resolved.", "Payout method and any tax documentation are agreed individually before a partner is activated.", "Participation does not create an employment relationship and may be ended in case of misuse."],
    finalTitle: "Know a business LinkedLab could help?", finalText: "Apply in a few minutes. After review, you receive your personal referral code.", privacyLink: "Privacy policy"
  },
  es: {
    seoTitle: "Programa de colaboradores LinkedLab | 50 € por cliente",
    seoDescription: "Recomienda LinkedLab y recibe 50 € por cada nuevo cliente confirmado y de pago, hasta un máximo de 500 €.",
    kicker: "Programa de colaboradores",
    title: "Buenos contactos. Recomendaciones claras. Comisión justa.",
    intro: "Recomienda LinkedLab a negocios que necesiten una web profesional o un sistema digital sencillo. Recibes 50 € por cada nuevo cliente confirmado y de pago.",
    primaryCta: "Solicitar ser colaborador", secondaryCta: "Cómo funciona",
    metrics: [["50 €", "por nuevo cliente válido"], ["500 €", "máximo por colaborador"], ["0 €", "de cuota de participación"]],
    howKicker: "Proceso sencillo", howTitle: "Tres pasos para cobrar tu comisión.", howText: "Sin plataforma ni panel ficticio: revisión personal, un código único y una confirmación verificable.",
    steps: [["01", "Solicita acceso", "Envía el formulario breve. LinkedLab revisa personalmente cada solicitud."], ["02", "Recomienda", "Tras la aprobación recibes un código único y un enlace para compartir con tus contactos."], ["03", "Recibe 50 €", "La comisión se genera cuando el cliente recomendado confirma y paga su proyecto."]],
    calculatorKicker: "Calculadora de comisión", calculatorTitle: "¿Cuánto pueden valer tus recomendaciones?", calculatorText: "Mueve el control. El límite es de diez nuevos clientes válidos.", clientsLabel: "Nuevos clientes válidos", earningsLabel: "Comisión posible", calculatorNote: "Una consulta por sí sola no genera comisión. Solo cuentan los proyectos confirmados y pagados, sin cancelación ni reembolso.",
    audienceKicker: "Para quién es", audienceTitle: "Ideal para personas con buenos contactos profesionales.", audienceText: "El programa está abierto a personas y pequeños negocios que puedan recomendar LinkedLab de forma creíble.",
    profiles: [["Freelancers y consultores", "Si tus clientes suelen necesitar ayuda con su web, SEO o procesos digitales."], ["Agencias y creativos", "Si un proyecto queda fuera de tus servicios y quieres recomendar a un colaborador fiable."], ["Conectores locales", "Si conectas a emprendedores, asociaciones o profesionales de tu zona."], ["Clientes satisfechos", "Si quieres compartir tu experiencia con LinkedLab con otros negocios."]],
    formKicker: "Solicitud", formTitle: "Hazte colaborador.", formText: "Cuéntanos brevemente quién eres y cómo recomendarías LinkedLab. La revisión y aprobación son manuales.",
    fields: { name: "Nombre o empresa", email: "Correo electrónico", channel: "Canal de contacto preferido (opcional)", activity: "Actividad", message: "Mensaje breve (opcional)" },
    placeholders: { name: "Tu nombre o empresa", email: "nombre@ejemplo.com", channel: "WhatsApp, teléfono, Instagram …", message: "¿Cómo recomendarías LinkedLab?" },
    activities: ["Selecciona una opción", "Freelancer / consultor", "Agencia / negocio creativo", "Red local", "Cliente actual", "Otro"],
    submit: "Enviar solicitud", sending: "Enviando …", success: "Gracias. Tu solicitud se ha enviado. Te responderemos después de revisarla personalmente.",
    formNote: "Al enviar aceptas que tratemos tus datos para revisar la solicitud. Consulta la política de privacidad para más información.",
    faqKicker: "Preguntas frecuentes", faqTitle: "Todo claro antes de empezar.",
    faqs: [["¿Cuándo cuenta una recomendación?", "Cuando un nuevo cliente usa tu código personal, confirma un proyecto con LinkedLab y se recibe el pago acordado."], ["¿Se paga por un contacto o lead?", "No. La comisión solo se genera con un nuevo cliente confirmado y de pago."], ["¿Cuál es la comisión?", "50 € por cada nuevo cliente válido, hasta diez clientes o 500 € en total por colaborador."], ["¿Qué ocurre si hay cancelación o reembolso?", "No se paga comisión por proyectos cancelados o reembolsados. Cualquier pago previsto se ajustará en consecuencia."], ["¿Cómo se atribuye una recomendación?", "Mediante tu código o enlace personal. El código se conserva durante la sesión del navegador y se envía a LinkedLab al contactar."], ["¿Hay un panel de colaboradores?", "Todavía no. En esta primera versión, las aprobaciones, confirmaciones y pagos se gestionan personalmente y se registran de forma manual."]],
    termsTitle: "Condiciones claras", terms: ["La participación es gratuita y se aprueba individualmente.", "Cada nuevo cliente solo puede asignarse a una recomendación.", "La comisión se confirma tras el pago y cuando se haya resuelto cualquier cancelación o reembolso.", "La forma de pago y la documentación fiscal necesaria se acuerdan antes de activar al colaborador.", "La participación no crea una relación laboral y puede terminarse en caso de uso indebido."],
    finalTitle: "¿Conoces un negocio al que LinkedLab puede ayudar?", finalText: "Solicita acceso en pocos minutos. Tras la revisión recibirás tu código personal.", privacyLink: "Política de privacidad"
  }
};
